### ISSUE TITLE
Buttons in main menu is not drawn correct.

### ISSUE THREAD

**Issue by InMyOrbit** [makerspace/memberbooth#74] opened 2020-10-01 08:30 UTC
There is an extra square drawn above each button in the main menu.

![image](https://user-images.githubusercontent.com/4609724/94786241-fe550e00-03d0-11eb-9449-95e7c09de6ca.png)

**Comment by emanuelen5** [comment] 2020-10-01 09:28
Duplicate of #73  😜

**Closed by emanuelen5** 2020-10-01 09:28 UTC
